name: Pull Request
on: [pull_request]
jobs:
  pull_request:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Check size
        run: npm run size
